@extends('layouts.app')

@section('content')
<section class="hero" @if($heroBanner) style="background-image:linear-gradient(90deg,rgba(0,0,0,.78),rgba(0,0,0,.12)),url('{{ $heroBanner->image_path }}');background-size:cover;background-position:center" @endif><div><span class="product-tag">{{ $heroBanner?->subtitle ?? 'Colección 01 · Bogotá' }}</span><h1>{{ $heroBanner?->title ?? 'Built for after dark.' }}</h1><p>Streetwear de edición limitada. Siluetas honestas, materiales pesados y una actitud sin ruido.</p><a class="button secondary" href="{{ $heroBanner?->link_url ?: route('products.index') }}">Comprar ahora</a></div></section>

<section class="feature-strip"><div>Envío nacional<br><span class="muted">Gratis desde $250.000</span></div><div>Pago seguro<br><span class="muted">Protegido por Bold</span></div><div>Cambios simples<br><span class="muted">Hasta 30 días</span></div><div>Atención real<br><span class="muted">Lun–Vie 9–18h</span></div></section>

<section class="section"><div class="section-header"><h2>Shop by category</h2><a href="{{ route('products.index') }}">Ver todo</a></div><div class="grid">@forelse($categories as $category)<a class="category-card" style="background:url('https://images.unsplash.com/{{ $category->image_path ?? 'photo-1521572163474-6864f9cf17ab' }}?auto=format&fit=crop&w=800&q=85') center/cover" href="{{ route('products.index', ['category' => $category->slug]) }}"><span>{{ $category->name }}<br><small class="muted">Shop now →</small></span></a>@empty<p class="muted">Próximamente.</p>@endforelse</div></section>

<section class="section"><div class="section-header"><h2>Trending now</h2><a href="{{ route('products.index') }}">Ver catálogo</a></div><div class="grid">@forelse($featuredProducts as $product)<article class="card"><a href="{{ route('products.show', $product) }}"><img src="{{ $product->images[0] ?? 'https://placehold.co/600x800?text=District' }}" alt="{{ $product->name }}"></a><div class="card-body"><h3>{{ $product->name }}</h3><p class="price">${{ number_format($product->price, 0, ',', '.') }} COP</p><button data-add-to-cart data-product-id="{{ $product->id }}" data-product-name="{{ $product->name }}" data-product-price="{{ $product->price }}" data-product-image="{{ $product->images[0] ?? '' }}" data-product-stock="{{ $product->stock }}">Añadir</button></div></article>@empty<p class="muted">Próximamente llegan nuevos drops.</p>@endforelse</div></section>

<section class="lookbook"><div><span class="product-tag">Drop limitado</span><h2>HECHO PARA LA CIUDAD.</h2><p>Prendas con presencia. Diseñadas para rotar, combinar y durar.</p><a class="button secondary" href="{{ route('products.index', ['category' => 'hoodies']) }}">Explorar hoodies</a></div><img src="https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1000&q=85" alt="Editorial de moda urbana"></section>

<section class="section"><div class="section-header"><h2>La marca</h2></div><p style="max-width:720px" class="muted">NOIR DISTRICT nace para vestir la energía de la ciudad. Trabajamos piezas funcionales, volúmenes precisos y detalles que funcionan de día o de noche. Escríbenos a <a href="mailto:hola@noirdistrict.co"><strong>hola@noirdistrict.co</strong></a> o síguenos en <a href="https://instagram.com" rel="noopener noreferrer" target="_blank"><strong>@noirdistrict</strong></a>.</p></section>
@endsection
